/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SecurityRouteRouteImport } from './routes/_security/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityScanRouteImport } from './routes/_security/scan'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvitationsIndexRouteImport } from './routes/_authenticated/invitations/index'
import { Route as InviteQrTokenRouteImport } from './routes/invite/qr/$token'
import { Route as AuthenticatedInvitationsNewRouteImport } from './routes/_authenticated/invitations/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRouteRoute = SecurityRouteRouteImport.update({
  id: '/_security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityScanRoute = SecurityScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => SecurityRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsIndexRoute =
  AuthenticatedInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InviteQrTokenRoute = InviteQrTokenRouteImport.update({
  id: '/invite/qr/$token',
  path: '/invite/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvitationsNewRoute =
  AuthenticatedInvitationsNewRouteImport.update({
    id: '/invitations/new',
    path: '/invitations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/scan': typeof SecurityScanRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/invite/qr/$token': typeof InviteQrTokenRoute
  '/invitations/': typeof AuthenticatedInvitationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/scan': typeof SecurityScanRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/invite/qr/$token': typeof InviteQrTokenRoute
  '/invitations': typeof AuthenticatedInvitationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_security': typeof SecurityRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_security/scan': typeof SecurityScanRoute
  '/_authenticated/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/invite/qr/$token': typeof InviteQrTokenRoute
  '/_authenticated/invitations/': typeof AuthenticatedInvitationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/payments'
    | '/reservations'
    | '/scan'
    | '/invitations/new'
    | '/invite/qr/$token'
    | '/invitations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/payments'
    | '/reservations'
    | '/scan'
    | '/invitations/new'
    | '/invite/qr/$token'
    | '/invitations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_security'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/payments'
    | '/_authenticated/reservations'
    | '/_security/scan'
    | '/_authenticated/invitations/new'
    | '/invite/qr/$token'
    | '/_authenticated/invitations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SecurityRouteRoute: typeof SecurityRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteQrTokenRoute: typeof InviteQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_security': {
      id: '/_security'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SecurityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_security/scan': {
      id: '/_security/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof SecurityScanRouteImport
      parentRoute: typeof SecurityRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations/': {
      id: '/_authenticated/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof AuthenticatedInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/qr/$token': {
      id: '/invite/qr/$token'
      path: '/invite/qr/$token'
      fullPath: '/invite/qr/$token'
      preLoaderRoute: typeof InviteQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitations/new': {
      id: '/_authenticated/invitations/new'
      path: '/invitations/new'
      fullPath: '/invitations/new'
      preLoaderRoute: typeof AuthenticatedInvitationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedInvitationsNewRoute: typeof AuthenticatedInvitationsNewRoute
  AuthenticatedInvitationsIndexRoute: typeof AuthenticatedInvitationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedInvitationsNewRoute: AuthenticatedInvitationsNewRoute,
  AuthenticatedInvitationsIndexRoute: AuthenticatedInvitationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SecurityRouteRouteChildren {
  SecurityScanRoute: typeof SecurityScanRoute
}

const SecurityRouteRouteChildren: SecurityRouteRouteChildren = {
  SecurityScanRoute: SecurityScanRoute,
}

const SecurityRouteRouteWithChildren = SecurityRouteRoute._addFileChildren(
  SecurityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SecurityRouteRoute: SecurityRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteQrTokenRoute: InviteQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
